-- Taxas de salão (serviço / couvert / garçom) + pessoas na comanda

CREATE TYPE "RestaurantFeeMode" AS ENUM ('PERCENT', 'FIXED');

ALTER TABLE "Company"
  ADD COLUMN IF NOT EXISTS "serviceFeeEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "serviceFeeMode" "RestaurantFeeMode" NOT NULL DEFAULT 'PERCENT',
  ADD COLUMN IF NOT EXISTS "serviceFeeValue" DECIMAL(14, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "couvertEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "couvertMode" "RestaurantFeeMode" NOT NULL DEFAULT 'FIXED',
  ADD COLUMN IF NOT EXISTS "couvertValue" DECIMAL(14, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "waiterTipEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "waiterTipMode" "RestaurantFeeMode" NOT NULL DEFAULT 'PERCENT',
  ADD COLUMN IF NOT EXISTS "waiterTipValue" DECIMAL(14, 4) NOT NULL DEFAULT 0;

ALTER TABLE "Sale"
  ADD COLUMN IF NOT EXISTS "serviceFeeAmount" DECIMAL(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "couvertAmount" DECIMAL(14, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "waiterTipAmount" DECIMAL(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE "ServiceTab"
  ADD COLUMN IF NOT EXISTS "guestCount" INTEGER NOT NULL DEFAULT 1;
